class DataSports {
  final String team1;
  final String team2;
  final int score1;
  final int score2;
  final String location;
  final int numBettors;
  final double totalBetAmount;
  final String imageUrl;
  final String sportType;

  DataSports({
    required this.team1,
    required this.team2,
    required this.score1,
    required this.score2,
    required this.location,
    required this.numBettors,
    required this.totalBetAmount,
    required this.imageUrl,
    required this.sportType,
  });
}

final List<DataSports> sportsDataList = [
  DataSports(
    team1: "NY Yankees",
    team2: "Boston Red Sox",
    score1: 5,
    score2: 3,
    location: "Yankee Stadium",
    numBettors: 1250,
    totalBetAmount: 55000.0,
    imageUrl: "assets/images/default_baseball.png",
    sportType: "Baseball",
  ),
  DataSports(
    team1: "LA Dodgers",
    team2: "SF Giants",
    score1: 2,
    score2: 4,
    location: "Dodger Stadium",
    numBettors: 980,
    totalBetAmount: 42000.0,
    imageUrl: "assets/images/default_baseball.png",
    sportType: "Baseball",
  ),
  DataSports(
    team1: "Chicago Cubs",
    team2: "St. Louis Cardinals",
    score1: 3,
    score2: 7,
    location: "Wrigley Field",
    numBettors: 1050,
    totalBetAmount: 48000.0,
    imageUrl: "assets/images/default_baseball.png",
    sportType: "Baseball",
  ),
  DataSports(
    team1: "Los Angeles Angels",
    team2: "Texas Rangers",
    score1: 4,
    score2: 5,
    location: "Angel Stadium",
    numBettors: 920,
    totalBetAmount: 40000.0,
    imageUrl: "assets/images/default_baseball.png",
    sportType: "Baseball",
  ),
  DataSports(
    team1: "Real Madrid",
    team2: "FC Barcelona",
    score1: 2,
    score2: 1,
    location: "Santiago Bernabéu",
    numBettors: 5420,
    totalBetAmount: 250000.0,
    imageUrl: "assets/images/default_futbol.png",
    sportType: "Soccer",
  ),
  DataSports(
    team1: "Manchester United",
    team2: "Liverpool",
    score1: 0,
    score2: 0,
    location: "Old Trafford",
    numBettors: 4800,
    totalBetAmount: 220000.0,
    imageUrl: "assets/images/default_futbol.png",
    sportType: "Soccer",
  ),
  DataSports(
    team1: "Chelsea",
    team2: "Arsenal",
    score1: 1,
    score2: 2,
    location: "Stamford Bridge",
    numBettors: 5200,
    totalBetAmount: 240000.0,
    imageUrl: "assets/images/default_futbol.png",
    sportType: "Soccer",
  ),
  DataSports(
    team1: "Juventus",
    team2: "Napoli",
    score1: 2,
    score2: 2,
    location: "Allianz Stadium",
    numBettors: 4700,
    totalBetAmount: 215000.0,
    imageUrl: "assets/images/default_futbol.png",
    sportType: "Soccer",
  ),
  DataSports(
    team1: "LA Lakers",
    team2: "Boston Celtics",
    score1: 110,
    score2: 105,
    location: "Staples Center",
    numBettors: 3200,
    totalBetAmount: 150000.0,
    imageUrl: "assets/images/default_basketball.png",
    sportType: "Basketball",
  ),
  DataSports(
    team1: "Golden State Warriors",
    team2: "Chicago Bulls",
    score1: 95,
    score2: 102,
    location: "Chase Center",
    numBettors: 2900,
    totalBetAmount: 135000.0,
    imageUrl: "assets/images/default_basketball.png",
    sportType: "Basketball",
  ),
  DataSports(
    team1: "Boston Celtics",
    team2: "Philadelphia 76ers",
    score1: 105,
    score2: 98,
    location: "TD Garden",
    numBettors: 3300,
    totalBetAmount: 155000.0,
    imageUrl: "assets/images/default_basketball.png",
    sportType: "Basketball",
  ),
  DataSports(
    team1: "Milwaukee Bucks",
    team2: "Brooklyn Nets",
    score1: 112,
    score2: 108,
    location: "Fiserv Forum",
    numBettors: 2950,
    totalBetAmount: 140000.0,
    imageUrl: "assets/images/default_basketball.png",
    sportType: "Basketball",
  ),
  DataSports(
    team1: "Canelo Álvarez",
    team2: "Gennady Golovkin",
    score1: 115,
    score2: 113,
    location: "T-Mobile Arena",
    numBettors: 6800,
    totalBetAmount: 300000.0,
    imageUrl: "assets/images/default_boxing.png",
    sportType: "Boxing",
  ),
  DataSports(
    team1: "Tyson Fury",
    team2: "Deontay Wilder",
    score1: 116,
    score2: 111,
    location: "MGM Grand Garden Arena",
    numBettors: 7200,
    totalBetAmount: 320000.0,
    imageUrl: "assets/images/default_boxing.png",
    sportType: "Boxing",
  ),
  DataSports(
    team1: "Deontay Wilder",
    team2: "Andy Ruiz Jr.",
    score1: 114,
    score2: 112,
    location: "Staples Center",
    numBettors: 7100,
    totalBetAmount: 325000.0,
    imageUrl: "assets/images/default_boxing.png",
    sportType: "Boxing",
  ),
  DataSports(
    team1: "Terence Crawford",
    team2: "Errol Spence Jr.",
    score1: 115,
    score2: 113,
    location: "AT&T Stadium",
    numBettors: 7400,
    totalBetAmount: 335000.0,
    imageUrl: "assets/images/default_boxing.png",
    sportType: "Boxing",
  ),
  DataSports(
    team1: "Houston Astros",
    team2: "Atlanta Braves",
    score1: 6,
    score2: 2,
    location: "Minute Maid Park",
    numBettors: 1100,
    totalBetAmount: 50000.0,
    imageUrl: "assets/images/default_baseball.png",
    sportType: "Baseball",
  ),
  DataSports(
    team1: "Seattle Mariners",
    team2: "Toronto Blue Jays",
    score1: 1,
    score2: 0,
    location: "Rogers Centre",
    numBettors: 850,
    totalBetAmount: 38000.0,
    imageUrl: "assets/images/default_baseball.png",
    sportType: "Baseball",
  ),
  DataSports(
    team1: "Paris Saint-Germain",
    team2: "Olympique Marseille",
    score1: 3,
    score2: 1,
    location: "Parc des Princes",
    numBettors: 5100,
    totalBetAmount: 230000.0,
    imageUrl: "assets/images/default_futbol.png",
    sportType: "Soccer",
  ),
  DataSports(
    team1: "AC Milan",
    team2: "Inter Milan",
    score1: 1,
    score2: 1,
    location: "San Siro",
    numBettors: 4600,
    totalBetAmount: 210000.0,
    imageUrl: "assets/images/default_futbol.png",
    sportType: "Soccer",
  ),
  DataSports(
    team1: "Miami Heat",
    team2: "Dallas Mavericks",
    score1: 102,
    score2: 98,
    location: "AmericanAirlines Arena",
    numBettors: 3100,
    totalBetAmount: 145000.0,
    imageUrl: "assets/images/default_basketball.png",
    sportType: "Basketball",
  ),
  DataSports(
    team1: "Phoenix Suns",
    team2: "Milwaukee Bucks",
    score1: 108,
    score2: 112,
    location: "Footprint Center",
    numBettors: 2800,
    totalBetAmount: 130000.0,
    imageUrl: "assets/images/default_basketball.png",
    sportType: "Basketball",
  ),
  DataSports(
    team1: "Errol Spence Jr.",
    team2: "Terence Crawford",
    score1: 114,
    score2: 116,
    location: "T-Mobile Arena",
    numBettors: 7000,
    totalBetAmount: 310000.0,
    imageUrl: "assets/images/default_boxing.png",
    sportType: "Boxing",
  ),
  DataSports(
    team1: "Anthony Joshua",
    team2: "Oleksandr Usyk",
    score1: 113,
    score2: 115,
    location: "Tottenham Hotspur Stadium",
    numBettors: 7300,
    totalBetAmount: 330000.0,
    imageUrl: "assets/images/default_boxing.png",
    sportType: "Boxing",
  ),
];
